### PR TITLE
Updating with latest changes from v3.0.0 w.i.p

### PR DESCRIPTION
**Pull request by Marzogh**

### CODE REVIEW

**Comment by VitorBoss** [comment]
Thanks in advance.
Is possible to add an option to use another SPI port? STM32 devices have up to 6 and your code only work on SPI1. Thank you.

**Comment by Marzogh** [comment]
I'll see if I can incorporate that in. I've never actually tested this library with an STM32 board. Is there a particular board that you could recommend I start with?

**Comment by VitorBoss** [comment]
Yes, Blue Pill is about $3 and Maple Mini too. I have successfully used in STM32F407VET6 board with a W25Q64 memory on SPI1. For Blue pill and maple mini use this https://github.com/rogerclarkmelbourne/Arduino_STM32

**Comment by Marzogh** [comment]
Thanks. I've just ordered a blue pill board off eBay and will work on it once it gets here. :)

I'll raise this as an issue as well, so you can follow any progress there.

**Pull request merged**
