### PR TITLE
Final code for v3.0.0 release

### PR DESCRIPTION
**Pull request by Marzogh**

### CODE REVIEW

**Comment by Marzogh** [comment]
@thedub2001, This is the final code ('stable' branch) going into v3.0.0 could you check to see if it works with the W25Q256? Thanks!

@boseji, Can you please confirm that v3.0.0 code from the 'stable' branch works with the RTL8195A? Once you confirm that, I can go ahead and make RTL8195A support official. 😃  If you want to add support for any new boards please do so on the 'development' branch and I'll roll that into the next release.

**Comment by boseji** [comment]
Sure will check this out tonight and confirm.

**Comment by Marzogh** [comment]
Thanks!

**Comment by boseji** [comment]
I have just checked out the Development Branch against RTL8195 with W25Q128FV there are some problems.
 - `FlashDiagnostics` completely crahes
 - `TestFlash` is not able to write to Flash properly. Both Page and Word write fail.

Not yet sure whats wrong. These are my iniital findings on the RTL8195.
Need to look into this in detail.

**Comment by Marzogh** [comment]
Hmmm... I'll hold off on the release till the end of next week to give you time. Please let me know if you need more time. 🙂

**Comment by boseji** [comment]
It look like some thing is broken from the SDK side I mean the release 2.0.2 of the tool-chain .
The access to SPI settings is causing a hard fault situation in RTL8195.

I would recommend that we drop official support for RTL8195 as of v3.0.0
So that there is no delay in release.

In the mean time I would work on the development branch to see what exactly went wrong.
Then in the next release if my development side is fixed with RTL8195 specific changes.
We can merge official support for RTL8195 again.

Please take this forward.

**Comment by thedub2001** [comment]
Hello !
I haves tested the "stable" branch with W25Q256.
Everything is OK, here is the serial output : 
```
Initialising Flash memory..........
Chip Diagnostics initiated.

No Chip size defined by user



--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                    SPIFlash Library version: 3.0.0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                Get ID
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
			JEDEC ID: ef4019h
			Manufacturer ID: efh
			Memory Type: 40h
			Capacity: 33554432 bytes
			Maximum pages: 131072
			Unique ID: 2200514064491264, 64A4A75B1B232300
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

			Erase Chip: 		Data I/O test PASS			Time: 72.351 s
			Erase 64KB Block: 	Data I/O test PASS			Time: 240 us
			Erase 32KB Block: 	Data I/O test PASS			Time: 280 us
			Erase 4KB Sector: 	Data I/O test PASS			Time: 272 us

			Byte: 			Data I/O test PASS			Write Time: 336 us,	Read Time: 136 us
			Char: 			Data I/O test PASS			Write Time: 328 us,	Read Time: 120 us
			Word: 			Data I/O test PASS			Write Time: 352 us,	Read Time: 128 us
			Short: 			Data I/O test PASS			Write Time: 360 us,	Read Time: 128 us
			ULong: 			Data I/O test PASS			Write Time: 384 us,	Read Time: 144 us
			Long: 			Data I/O test PASS			Write Time: 384 us,	Read Time: 144 us
			Float: 			Data I/O test PASS			Write Time: 376 us,	Read Time: 136 us
			Struct: 		Data I/O test PASS			Write Time: 136 us,	Read Time: 136 us
			Byte Array: 		Data I/O test PASS			Write Time: 5.112 ms,	Read Time: 848 us
			String: 		Data I/O test PASS			Write Time: 424 us,	Read Time: 152 us
			Power Down: 		Data I/O test PASS			Time: 160 us
			Power Up: 		Data I/O test PASS			Time: 136 us
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```
Great work! 😀

**Comment by Marzogh** [comment]
Thanks guys. I'll finish up with updating the API docs / wiki and then get the release out of the door this weekend. 🙂

**Comment by boseji** [comment]
I have been trying to get the flash to work with RTL8195. 
It looks like some dip in power to Flash chip during the Flash Diagnostics .
That was causing issues with flash testing.
I will try get a new board for the W25Q128FV with RTL8195.
Also will try to check the v2.7.0 one more time, since the Flash interface was working at that time.

**Pull request merged**
