### PR TITLE
Adding support for RTL8195A

### PR DESCRIPTION
**Pull request by boseji**
Hello,

Your library is an excellent work. It was very helpful.

I had tried to add the RTL8195A Support for your library.
This can be easily used for the Ameba IoT boards.
http://www.amebaiot.com/en/
http://www.amebaiot.com/en/boards/

Hope that you would like to add support for this chip.
I have marked all the changes feel free to modify the architecture if needed.

For testing out the build you can use configuration JSON:
https://github.com/Ameba8195/Arduino/raw/master/release/package_realtek.com_ameba_index.json

If you would like to change any things or need help in integration, 
Please do let me know. 
I wish to return the support as your library has helped me a lot.

Thanking you,

Warm Regards,
Boseji

### CODE REVIEW

**Comment by boseji** [comment]
Hi,

Thanks for the update,

I will take a look at the new branch and do a merge on my side.
Would test it out also on the 4MB flash just to be sure.

Regards,
Boseji

**Comment by boseji** [comment]
Hi,

Just tested out all the examples. They are all working.
There is some garbled output on Flash diagnostics example though.
However using the Flash Test example I have checked the raw writes and they work a charm.
It would be nice to have the sector erase option also in the Flash Test example.

One suggestion on the examples, it would be nice to keep the serial output small else it was difficult to fit in my one screen. May be some people might face this issue.

Other wise as earlier your library rocks !

Regards,
boseji

**Comment by Marzogh** [comment]
Thanks for sorting it out. I'll merge this into the next release. :)

I have the massive Serial output from my diagnostics & testFlash examples because they are my troubleshooting programs. Anyone who uses them, should, in theory be able to obtain highly granual results and be able to track down bugs that much more easily. Over time, as the library has gotten more complex, there's a lot more to test and display, so, unfortunately, the Serial output has gotten a bit bloated. I'll take what you've said into account though and see if I can tighten it up a bit :)

**Comment by boseji** [comment]
Thanks,
Will keep in mind the commenting things for next time.
Currently working on RTL8710 platform. I want to have the SPIFlash working for that also.
Would let you know once I have some head way there.

**Comment by Marzogh** [comment]
Cheers! Thanks for all the work :) Look forward to integrating the RTL8710 as well. :) Just make sure you grab all the base code from v2.6.0-w.i.p. Its the latest stable version of the code till v2.6.0 is released. :)

**Comment by boseji** [comment]
Thanks to you too for the good library !
I will take a pull. Sure I will raise the request once ready with RTL8710.

**Comment by Marzogh** [comment]
Always glad to help. :)

**Comment by Marzogh** [comment]
Just a heads up mate, v2.6.0 has been released into the wild. Could you please push your updates to the dev branch instead?

**Comment by boseji** [comment]
Will do that. I would take a pull and create the dev banch for the fork also to match parent.

**Pull request merged**
